- name:  Update and Configure Apache2 Servers
  hosts: gce_servers
  roles:
    - weareinteractive.openssl
    - weareinteractive.apache2
  vars:
    apache2_modules:
      - { id: ssl, state: present }
      - { id: mime, state: present }
      - { id: headers, state: present }
      - { id: rewrite, state: present }
    apache2_confs:
      - { id: php8.0-fpm, state: present}
    apache2_remove_default: yes
    openssl_generate_csr: yes
    openssl_self_signed:
      - name: artificialbelligerence
        country: "CA"
        state: "Ontario"
        city: "Toronto"
        organization: "Cognisian"
        unit: "Services Unit"
        email: seandchalmers@yahoo.ca
    apache2_sites:
      - id: artificialbelligerence.com
        name: artificialbelligerence.com
        state: present
        rules:
          - content_transform
          - mimes
          - expires
          - etag
          - compression
          - security_file_access
          - security_hosts
          - security_mime
          - security_signiture
          - security_technology
        add_webroot: yes
        redirect_to_ssl: yes
        ssl:
          port: 443
          key_name: artificialbelligerence
          cert_name: artificialbelligerence
