- name:  Update and Configure Apache2 Servers
  hosts: gce_servers
  roles:
    - weareinteractive.apache2
    - certbot
  vars:
    certbot_testmode: false
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_admin_email: seandchalmers@yahoo.ca
    
    certbot_install_method: package
    certbot_package: python3-certbot
    set_fact:
      certbot_script: certbot
      
    certbot_create_standalone_stop_services:
      - apache2
      
    certbot_certs:
      - name: artificialbelligerence.com
        domains:
          - artificialbelligerence.com
          - www.artificialbelligerence.com
    
    certbot_create_command: >-
      {{ certbot_script }} certonly --{{ certbot_create_method  }}
      {{ '--test-cert' if certbot_testmode else '' }}
      --noninteractive --agree-tos
      --email {{ cert_item.email | default(certbot_admin_email) }}
      {{ '--cert-name ' ~ cert_item.name if cert_item.name is defined
        else ''
      }}
      -d {{ cert_item.domains | join(',') }}
      {{ '--pre-hook /etc/letsencrypt/renewal-hooks/pre/stop_services'
        if certbot_create_standalone_stop_services
        else '' }}
      {{ '--post-hook /etc/letsencrypt/renewal-hooks/post/start_services'
        if certbot_create_standalone_stop_services
        else ''
      }}

    apache2_modules:
      - { id: ssl, state: present }
      - { id: mime, state: present }
      - { id: headers, state: present }
      - { id: rewrite, state: present }
    apache2_confs:
      - { id: php8.1-fpm, state: present}
    apache2_remove_default: yes
    apache2_sites:
      - id: artificialbelligerence.com
        name: artificialbelligerence.com
        state: present
        rules:
          - content_transform
          - mimes
          - expires
          - etag
          - compression
          - security_file_access
          - security_hosts
          - security_mime
          - security_signiture
          - security_technology
        add_webroot: yes
        redirect_to_ssl: yes
        ssl:
          port: 443
          key_name: privkey.pem
          cert_name: fullchain.pem
    apache2_certs_path: /etc/letsencrypt/live
    apache2_keys_path: /etc/letsencrypt/live
    
  tasks:
    - name: Change webroot perm to allow group writing
      file:
        dest: "{{ apache2_sites_basedir }}/{{ item.id }}/htdocs"
        mode: "0775"
      when: item.add_webroot is defined and item.add_webroot
      with_items: "{{ apache2_sites }}"
      
    - name: Create anon GitHub Actions local service account
      ansible.builtin.user:
        name: runner
        state: present
        append: false
        groups: 
          - "{{ apache_run_group }}"
        comment: Anon GitHub Actions local service account to copy files to website
    