# Update Server software on all hosts with general required packages
- name:  Update Servers
  hosts: all
  
  tasks:
    - name: Update APT repository
      ansible.builtin.apt:
        update_cache: yes
    
    - name: Upgrade installed packages
      ansible.builtin.apt:
        upgrade: yes

    - name: Install general tools
      ansible.builtin.apt:
        state: latest
        name:
          - dialog
          - man-db
          - apt-utils
          - apt-doc
          - vim
          - cowsay
          - git
          - sqlite3

# Update and Configure Web Server software
-  import_playbook: provision/apache2.yml
-  import_playbook: provision/fpm-php.yml